// Auto-generated by launch.ps1 from the contents of frames/ - do not edit by hand.
window.FRAMES = ["Amol.png","Bella.png","Hannah.png","James Acaster.png","James Blunt.png","Jerry.png","Joanne.png","Joe.png","Julie.png","Kenny.png","Leigh-Anne.png","Maya.png","Michael.png","Miranda.png","Myha\u0027la.png","Richard.png","Rob.png","Romesh.png","Ross.png","Sebastian.png","Sharon.png"];
window.X_SPRITE = "x.png";
